# Generated by Django 5.1.7 on 2025-04-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_detail',
            name='assigned_to',
        ),
    ]
