# Generated by Django 5.1.7 on 2025-04-17 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_employee_task_assigned_to_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_detail',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='tasks.task'),
        ),
    ]
