# Generated by Django 5.1.7 on 2025-04-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_detail_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to_employee',
            field=models.ManyToManyField(related_name='tasks', to='tasks.employee'),
        ),
    ]
